### ISSUE TITLE
USER STORY: <Set Up Project>

### ISSUE THREAD

**Issue by NatasaMiric** [NatasaMiric/feedme-api#10]
As a developer, I want to set up my project and deploy it so that I can start developing my app.

### Acceptance criteria
* Project  successfully running locally
* Project successfully  running on Heroku

### Tasks
- [ ] Install and configure libraries
- [ ] Connect to Cloudinary
- [ ] Create a Heroku app
- [ ] Create a new external database
- [ ] Connect an external database to Heroku
- [ ] Set environment variables
- [ ] Connect the project’s GitHub repo to Heroku
