### ISSUE TITLE
USER STORY:<Create user profile API>

### ISSUE THREAD

**Issue by NatasaMiric** [NatasaMiric/feedme-api#44]
As a **user** I can **create a profile** so that **I can store and share information about myself with other users** 
#33 

### Acceptance criteria
* Create a profile with a unique id every time user is created
* Retrieve a single profile
* Retrieve all profiles
* List all profiles
* Edit profile with a particular id

### Tasks
- [x] Create a profile app
- [x] Create a profile model
- [x] Create a profile serializer and view
- [x] Map to url
- [x] Add profile details view
- [ ] Add authentication, authorization method

**Comment by NatasaMiric** [comment]
![Image](https://user-images.githubusercontent.com/111435650/233095230-871bad0a-6004-4c8e-a801-2389e7de6fe2.png)
![Image](https://user-images.githubusercontent.com/111435650/233095232-82eb8db0-7c74-4bd0-9be9-c98af0ac50a1.png)
![Image](https://user-images.githubusercontent.com/111435650/233095231-4c9b8b03-ceab-453c-8638-71e54c1e42a3.png)

**Comment by NatasaMiric** [comment]
test profile details 

![Image](https://user-images.githubusercontent.com/111435650/233098280-cabb5ee9-0089-425e-942a-0e85e1acf968.png)

update

**Comment by NatasaMiric** [comment]
Test after adding isOwner permission, is_owner field false or true:
- as logged out user is-owner field is false on all profiles listed on the page
- as logged out user my profile detail shows is_owner false
- as logged in  user  is_owner field is true on the profile that is currently logged in and false on the rest of the profiles
- as logged in user, on the profile detail page of the logged-in user is_owner is true, and on the other user's profile false

![Image](https://user-images.githubusercontent.com/111435650/233126594-2a950e8a-7430-48bd-87b1-43a5e1a270d8.png)

![Image](https://user-images.githubusercontent.com/111435650/233126733-403715ad-ba78-4970-a781-11438d3b4574.png)



![Image](https://user-images.githubusercontent.com/111435650/233126740-528f4992-2b2c-4bf4-9764-95fe8a63a431.png)



![Image](https://user-images.githubusercontent.com/111435650/233126645-b1eda065-e545-4a2d-9bde-bb4f781711b6.png)
