### ISSUE TITLE
USER STORY:<Create recipes API>

### ISSUE THREAD

**Issue by NatasaMiric** [NatasaMiric/feedme-api#45]
As a **user** I can **store all recipes in a database** so that **I can manage them**
#2 

### Acceptance criteria 
* Create a new recipe with a unique id
* Can view the details of a specific recipe
* List all recipes
* Retrieve a recipe by id
* Update a recipe by id
* Delete a recipe by id

### Tasks 
- [x] Create a recipe app
- [x] Create a recipe model 
- [x]  Create a recipe serializer 
- [x]  Add image validation
- [x] Create a recipe  list view (get method to list all recipes and post method to create a recipe)
- [x] Create a recipe detail view
- [x] Add extra field for like id and bookmark id 
- [x] Add likes_count and comments_count fields
- [x] Test

**Comment by NatasaMiric** [comment]
Manual testing:
-list all recipes as logged out user
- list all recipes as logged in user
- get recipe detail of the logged in user
- update recipe
- delete recipe
- get recipe details of another user 



![Image](https://user-images.githubusercontent.com/111435650/233944452-0a83ec46-3b38-4bd3-a327-4094e3f4f46e.png)



![Image](https://user-images.githubusercontent.com/111435650/233944467-42611464-8bac-4650-8866-6ae4c1daa390.png)



![Image](https://user-images.githubusercontent.com/111435650/233944561-03926faf-220f-45bd-8b04-762cf776a6de.png)



![Image](https://user-images.githubusercontent.com/111435650/233944676-16193f24-ad1d-47f3-bb1f-052fb505f5b5.png)



![Image](https://user-images.githubusercontent.com/111435650/233944809-63a21b23-9611-46f7-8546-278dd79a4840.png)



![Image](https://user-images.githubusercontent.com/111435650/233945098-a3946a43-eb47-4431-a941-aa55d8091f52.png)



![Image](https://user-images.githubusercontent.com/111435650/233945331-16fa72b1-fc1c-46cb-8207-78bfec82017d.png)
