### ISSUE TITLE
USER STORY:<Create comment API>

### ISSUE THREAD

**Issue by NatasaMiric** [NatasaMiric/feedme-api#46]
As a **logged-in** user I can store comments in the database so that **I can retrieve, update and delete them**
 #8

### Acceptance criteria 
* List all comments
* Create a new comment with a unique id
* Retrieve a comment by a particular id
* Edit comment with by a particular id
* Delete a comment by a particular id

### Tasks
- [x] Create a comment app
- [x] Create a comment model
- [x] Create a comment serializer 
- [x] Create a comment view
- [x] Test

**Comment by NatasaMiric** [comment]
Manual testing:
- List all comments
- create a comment as logged in user
- update a comment that you own
- delete a comment that you own 
- comment detail view as logged-out user

![Image](https://user-images.githubusercontent.com/111435650/233832608-f14af9de-234e-42a6-a55b-850f7e0fbff1.png)



![Image](https://user-images.githubusercontent.com/111435650/233832610-36f91250-1daa-47c0-85d8-57ab31faef11.png)



![Image](https://user-images.githubusercontent.com/111435650/233832616-9eb294d1-d082-40c7-aefb-6e3a5ba1a284.png)



![Image](https://user-images.githubusercontent.com/111435650/233832619-f2ab12f3-7861-48dd-850a-1007a8098b9c.png)



![Image](https://user-images.githubusercontent.com/111435650/233832601-748406ae-1f89-4b6f-bc6e-eb30f0fb9856.png)
