### ISSUE TITLE
USER STORY:<Create Like API>

### ISSUE THREAD

**Issue by NatasaMiric** [NatasaMiric/feedme-api#47]
As a **user** I can **like a recipe** so that **I can  show my support to the author of the recipe**
#7 

### Acceptance criteria 
* List all likes
* Create a like
* Prevent duplicate likes
* Retrieve a like by id
* Update a like by id
* Delete a like by id

### Tasks
- [x] Create the likes app
- [x] Create the like model
- [x] Create the like serializer 
- [x] Create the like list view
- [x] Create like detail view
- [x] Test

**Comment by NatasaMiric** [comment]
Manual testing: ¨
-list all likes as logged in user
-list all likes as logged out user
- fetch a like by id as logged in user
-create a like as logged in user
- delete the like you own as logged in user
-  view like a 

![Image](https://user-images.githubusercontent.com/111435650/233835928-2e9578fd-fb58-40b6-9f4b-0bd7f8134ef2.png)



![Image](https://user-images.githubusercontent.com/111435650/233835931-0757f593-3096-4188-8cd4-bf88d47b2847.png)



![Image](https://user-images.githubusercontent.com/111435650/233836003-0a3e63ba-3aec-41cb-9457-b74fcf1a79f5.png)



![Image](https://user-images.githubusercontent.com/111435650/233836007-a2ee5c02-34b7-4753-894e-267a157dc67a.png)



![Image](https://user-images.githubusercontent.com/111435650/233836009-739715c4-e355-45bf-af7e-af17667f2eca.png)



![Image](https://user-images.githubusercontent.com/111435650/233836010-b3a774e7-0a92-4c1c-8aaf-aa607c2e510c.png)

detail from another user
