### ISSUE TITLE
USER STORY:<Create bookmark API>

### ISSUE THREAD

**Issue by NatasaMiric** [NatasaMiric/feedme-api#48]
As a **logged in user** I can **save/bookmark recipes**  so that **I can store in one place all recipes that I like the most**

### Acceptance criteria  
* List all bookmarked recipes that currently logged in user owns
* Bookmark recipe as logged in user
* Fetch bookmarked recipe by id 
* Delete bookmarked recipe

### Tasks 
- [x] Create Bookmarks app
- [x] Create Bookmark model
- [x] Create Bookmark serializer
- [x] Create bookmark list view 
- [x] Create bookmark detail view 
- [x] Test

**Comment by NatasaMiric** [comment]
Manual testing: 

- list all bookmarks as logged out user
- list all bookmarks as logged in user
- fetch a bookmark by id as logged-in user
- create a bookmark as logged in user
- delete the bookmark you own as logged in user
- fetch bookmark detail from another user
- duplicate bookmark handling



![Image](https://user-images.githubusercontent.com/111435650/233838273-117654a9-28dc-47f6-b162-aae2cd346d0d.png)



![Image](https://user-images.githubusercontent.com/111435650/233838282-6f8b49bb-ff03-4066-a266-c362ebd76093.png)



![Image](https://user-images.githubusercontent.com/111435650/233838299-f677be7b-aa0f-4214-87d5-6111d3b41166.png)



![Image](https://user-images.githubusercontent.com/111435650/233838391-2136fad1-2c4b-4f52-8932-96eea075b2e0.png)


![Image](https://user-images.githubusercontent.com/111435650/233838421-54658e34-868d-4c54-bf4d-eae895ffc22b.png)



![Image](https://user-images.githubusercontent.com/111435650/233838444-7683a9b3-14cf-40ca-93da-4c7e3280efc1.png)



![Image](https://user-images.githubusercontent.com/111435650/233838455-06f52c4f-ad55-46e8-8e58-c44933f03c65.png)
